packages:
  - apps/*
  - packages/*

catalog:
  '@automerge/automerge-repo': ^2.5.6
  '@tarstate/core': git+https://github.com/neftaly/tarstate.git#f26f5038b4703315b98487be715eed4b8e70fb97&path:/packages/core
  '@types/node': ^24.10.3
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  oxlint: 1.70.0
  oxlint-tsgolint: ^0.23.0
  playwright-core: ^1.57.0
  react: ^19.2.7
  react-dom: ^19.2.7
  typescript: ^6.0.3
  vite: ^7.3.5
  vite-plugin-wasm: ^3.6.0
