packages:
  - apps/*
  - packages/*

catalog:
  '@tarstate/core': git+https://github.com/neftaly/tarstate.git#3f1fe92e901ef70eb2a9dccdcfbe3028b422b87e&path:/packages/core
  '@types/node': ^24.10.3
  oxlint: 1.70.0
  oxlint-tsgolint: ^0.23.0
  typescript: ^6.0.3
  vite: ^7.3.5
  vite-plugin-pwa: ^1.3.0
