packages:
  - apps/*
  - packages/*

catalog:
  '@automerge/automerge': ^3.2.6
  '@tarstate/automerge': git+https://github.com/neftaly/tarstate.git#110d1dbb38881805e95f2619d9900b73b8121773&path:/packages/automerge
  '@tarstate/core': git+https://github.com/neftaly/tarstate.git#110d1dbb38881805e95f2619d9900b73b8121773&path:/packages/core
  '@types/node': ^24.10.3
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.2.0
  oxlint: 1.70.0
  oxlint-tsgolint: ^0.23.0
  react: ^19.2.7
  react-dom: ^19.2.7
  typescript: ^6.0.3
  vite: ^7.3.5
  vite-plugin-top-level-await: 1.6.0
  vite-plugin-wasm: 3.6.0
